name: 'FFXIV Sign'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 16,22 * * *'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade requests
          pip install selenium==3.141.0
          pip install lxml==4.5.1
          pip install requests==2.23.0
          pip install image==1.5.33
          pip install urllib3==1.26.4
      - name: 'chrome'
        run:  sudo apt-get install google-chrome
      - name: 'Start Sign'
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          AREA: ${{ secrets.AREA }}
        run: python main.py
